/**
 * One record from the processed HYG dataset.
 * Coordinates are in parsecs, origin = Sol.
 *
 * Generated by:  python3 scripts/process_hyg.py hygdata_v3.csv data/stars.json
 * Source:        https://github.com/astronexus/HYGDatabase
 */
export interface Star {
  /** HYG internal id */
  id: number
  /** Hipparcos catalogue number (null for Sol) */
  hip: number | null
  /** Common / proper name, null if none */
  name: string | null
  /** Bayer / Flamsteed designation (cleaned, no leading Flamsteed number) */
  bf: string | null
  /** Gliese / GJ catalogue designation */
  gl: string | null
  /** Position in parsecs from Sol, IAU J2000 galactic frame.
   *  gx → galactic centre, gy → galactic north (Three.js Y), gz → completes frame.
   *  Pre-rotated by process_hyg.py — no further transform needed at runtime. */
  gx: number
  gy: number
  gz: number
  /** Distance in light-years */
  dist_ly: number
  /** Apparent visual magnitude */
  mag: number
  /** First letter of Harvard spectral class: O B A F G K M */
  spect: string
}
